name: Docker Image CI Backend

on:
  workflow_run:
    workflows: [".NET_TESTS"]
    types:
      - completed
  workflow_dispatch:

jobs:
  push_backend_to_DockerHub:
    name: Push Backend Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONTEND }}

      - name: Build and push
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./
          file: "./Delightful Daily Dose/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-backend:latest
          secrets: |
            "JWTSecretKey=${{ secrets.JWT_SECRET_KEY }}"
            "JWTLifespan=${{ secrets.JWT_LIFESPAN }}"
            "EmailAddress=${{ secrets.APP_EMAIL_ADDRESS }}"
            "EmailPassword=${{ secrets.APP_EMAIL_PASSWORD }}"

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-backend:latest
          run: |
            echo "Running the docker image"
