name: Docker Image CI

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed
  workflow_dispatch:

jobs:      
  push_to_DockerHub:
      name: Push Images to DockerHub
      # The type of runner that the job will run on
      runs-on: ubuntu-latest      
      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN_FRONTEND }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./delightful-daily-dose-frontend
            file: ./Dockerfile
            push: true
            tags: delightfuldailydose:latest

        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            image: delightfuldailydose:latest
            run: |
              echo "Running the docker image"
              echo "Testing the nodejs app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}
