name: Docker Image CI

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed
  workflow_dispatch:

jobs:
  push_frontend_to_DockerHub:
    name: Push Frontend Images to DockerHub
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONTEND }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./delightful-daily-dose-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-frontend:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-frontend:latest
          run: |
            echo "Running the docker image"

  push_backend_to_DockerHub:
    name: Push Backend Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONTEND }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: "./Delightful Daily Dose/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-backend:latest

      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/delightfuldailydose-backend:latest
          run: |
            echo "Running the docker image"